#!/bin/bash

rm -f dist_trans.dat 

ls -d  cyc*/ | 
    sort -k1.4n | 
    xargs -I{} sh -c 'sort -k3n,3 {}/ranking | head -1' | 
    awk '{ split($1,arr,"-"); print arr[1],$3,$4 }' |
tee -a dist_trans.dat

