#!/bin/bash

yes | rm dist_trans.dat 

for c in `ls -d cyc*/`; do 
    sort -k3n,3 ${c}ranking | head -1 | awk '{ split($1,arr,"-"); print arr[1],$3, $4 }'>> dist_trans.dat
done 

cat dist_trans.dat | sort -k1n,1 > tmp
mv tmp dist_trans.dat

# plot by gnuplot
cat <<EOF | gnuplot
set terminal dumb
p "dist_trans.dat" u 1:2 w lp
EOF
